# Generated by Django 3.1.2 on 2020-10-30 08:15

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, default=0.0)),
                ('longitude', models.FloatField(blank=True, default=0.0)),
                ('dob', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('phone_activated', models.BooleanField(default=False)),
                ('phone_activation_code', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=200)),
                ('profile_image', models.ImageField(blank=True, upload_to='')),
                ('cover_photo', models.ImageField(blank=True, upload_to='')),
                ('facebook_link', models.CharField(blank=True, max_length=200)),
                ('twitter_link', models.CharField(blank=True, max_length=200)),
                ('instagram_link', models.CharField(blank=True, max_length=200)),
                ('youtube_link', models.CharField(blank=True, max_length=200)),
                ('linkedin_link', models.CharField(blank=True, max_length=200)),
                ('sendEmail', models.BooleanField(default=True)),
                ('sendSMS', models.BooleanField(default=True)),
                ('activation', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.AccountManager()),
            ],
        ),
    ]
