# Generated by Django 3.1.2 on 2020-10-30 13:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201030_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='research_data',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
