# Generated by Django 3.1.2 on 2020-11-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201030_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
