# Generated by Django 3.1.2 on 2020-11-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201104_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
