# Generated by Django 3.1.2 on 2020-11-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201105_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
