# Generated by Django 3.1.2 on 2020-11-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='photo',
            field=models.ImageField(upload_to='blog/static/blog'),
        ),
    ]
