# Generated by Django 3.1.2 on 2020-11-07 02:31

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201106_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogimages',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
