# Generated by Django 3.1.2 on 2020-11-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201107_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimages',
            name='address',
        ),
        migrations.RemoveField(
            model_name='blogimages',
            name='geolocation',
        ),
    ]
