# Generated by Django 3.1.2 on 2020-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201107_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='displayphoto',
            field=models.ImageField(null=True, upload_to='blog/static/blog'),
        ),
    ]
