# Generated by Django 3.1.2 on 2020-11-11 01:33

from django.db import migrations, models
import django_google_maps.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_displayphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', tinymce.models.HTMLField(null=True)),
                ('privacy_policy', tinymce.models.HTMLField(null=True)),
                ('address', django_google_maps.fields.AddressField(max_length=200, null=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
