# Generated by Django 3.1.2 on 2020-11-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201111_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='published_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
