# Generated by Django 3.1.2 on 2020-11-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201117_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='alias',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='alias',
            field=models.SlugField(max_length=200),
        ),
    ]
