# Generated by Django 3.1.2 on 2020-11-22 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20201118_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='authored_by',
            field=models.ForeignKey(db_column='authored_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_authored_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='edited_by',
            field=models.ForeignKey(db_column='edited_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_by',
            field=models.ForeignKey(db_column='published_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='researched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='researched_by',
            field=models.ForeignKey(db_column='researched_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_researched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
