# Generated by Django 3.1.2 on 2020-11-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201122_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='authored',
            field=models.BooleanField(default=False, verbose_name='Authoring complete'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Editing complete'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='researched',
            field=models.BooleanField(default=False, verbose_name='Research complete'),
        ),
    ]
