# Generated by Django 3.1.2 on 2020-11-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201122_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimages',
            name='address',
        ),
        migrations.RemoveField(
            model_name='blogimages',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='blog',
            name='researched',
            field=models.BooleanField(default=False, verbose_name='Research completed'),
        ),
    ]
